services:
  - type: web
    name: road-to-sub5
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    preDeployCommand: python init_db.py
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: GARMIN_EMAIL
        sync: false
      - key: GARMIN_PASSWORD
        sync: false
      - key: FLASK_SECRET_KEY
        generateValue: true
